MONGO_URI = "Your url link";
FRONTEND_URL = "http://localhost:<port>";




CLOUDINARY_CLOUD_NAME = <YOUR_CLOUDINARY_CLOUD_NAME>
CLOUDINARY_API_KEY = <YOUR_CLOUDINARY_API_KEY>
CLOUDINARY_API_SECRET = <YOUR_CLOUDINARY_API_SECRET>

SMPT_HOST = <YOUR_SMPT_HOST>
SMPT_PORT = <YOUR_SMPT_PORT>
SMPT_USERNAME = <YOUR_SMPT_USERNAME>
SMPT_PASSWORD = <YOUR_SMPT_PASSWORD>
SMPT_FROM_EMAIL = <YOUR_SMPT_FROM_EMAIL>
